### ISSUE TITLE
Can't Find Documentation For Jest Matchers

### ISSUE THREAD

**Issue by machineghost** [FormidableLabs/enzyme-matchers#247] opened 2018-07-18 16:57 UTC
The Jest-Enzyme readme doesn't list any of the library's matchers anywhere, it only explains how to set it up.  Being able to set up a library is great, but it's also important that people understand how to use it ;)

I realize the matchers are documented on the main readme, but if you find the jest-enzyme readme from Google it'd be helpful if it at least included a link back to the main readme with a note that you can find the matchers there.

**Comment by blainekasten** [comment] 2018-08-02 04:08
Dupe of #236

**Closed by blainekasten** 2018-08-02 04:08 UTC
