### ISSUE TITLE
message is not a function

### ISSUE THREAD

**Issue by codeuniquely** [FormidableLabs/enzyme-matchers#183] opened 2018-01-04 15:09 UTC
When  i perform a check using something like this:

```
const component = (
  shallow(<Grid className="test"><Tile>Hello</Tile></Grid>)
 );
 expect(component).toHaveClassName('test grid');
```

and the expect fails because the className does not match what declared with  "test grid" (when i've only set test as above,  I get the somewhat cryptic message of:

*TypeError: message is not a function*

I can them look at component.html() and see what i've done wrong and correct the expect expression and then the test will pass, and enzyme / jest will continue with other tests

The error happens the same way on other matcher functions - when a match is not found..
e.g.
toHaveStyle('background-color', '#000000')

Here is a copy of the jest file pointed to by 
```
"setupTestFrameworkScriptFile": "<rootDir>/src/extendTests.js"
```

extendTest.js
```
import * as enzymeMatchers from 'enzyme-matchers';
expect.extend(enzymeMatchers);
```

Am I missing something then enables more informative 'Error Messages' when a test fails ...
(may with the normal  Expected:  Received: Jest messaging ...

**Comment by blainekasten** [comment] 2018-01-26 19:51
@codeuniquely is there any reason you are not using `jest-enzyme` ? 

`jest-enzyme` is a wrapper around `enzyme-matchers` and properly sets up the `expect.extend` calls

**Comment by blainekasten** [comment] 2018-02-05 16:38
@codeuniquely I'm going to close this for now. I believe the problem is that you are not using the test-runner libs. If you have any further questions or concerns please comment here and we can discuss.

**Closed by blainekasten** 2018-02-05 16:38 UTC
Labels: question
